apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quizup-prod
resources:
  - deployment.yml
  - service.yml
  - ingress.yml
images:
  - name: ghcr.io/quizup-organization/frontend
    newTag: "1.0.0"

