apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quizup-identity-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_USERNAME: CHANGE_ME
    QUIZUP_DB_PASSWORD: CHANGE_ME
    QUIZUP_RABBITMQ_USERNAME: CHANGE_ME
    QUIZUP_RABBITMQ_PASSWORD: CHANGE_ME
    QUIZUP_OAUTH2_GOOGLE_CLIENT_ID: CHANGE_ME
    QUIZUP_OAUTH2_GOOGLE_SECRET: CHANGE_ME
    QUIZUP_IDENTITY_SERVER_CLIENT_SECRET: CHANGE_ME
    QUIZUP_IDENTITY_ADMIN_CLIENT_SECRET: CHANGE_ME
  template:
    metadata:
      name: quizup-identity-secret
      namespace: quizup-prod
    type: Opaque

