apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quizup-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/quizup-organization/quizup-deploy.git
    targetRevision: main
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
