apiVersion: v1
kind: Service
metadata:
  name: profile
  namespace: quizup-prod
  labels:
    app: profile
spec:
  selector:
    app: profile
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
