apiVersion: v1
kind: Service
metadata:
  name: challenge
  namespace: quizup-prod
  labels:
    app: challenge
spec:
  selector:
    app: challenge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
