apiVersion: apps/v1
kind: Deployment
metadata:
  name: theme
  namespace: quizup-prod
  labels:
    app: theme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theme
  template:
    metadata:
      labels:
        app: theme
    spec:
      containers:
        - name: theme
          image: ghcr.io/quizup-organization/theme:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
