apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: quizup-theme-secret
  namespace: quizup-prod
spec:
  encryptedData:
    QUIZUP_DB_USERNAME: CHANGE_ME
    QUIZUP_DB_PASSWORD: CHANGE_ME
    QUIZUP_RABBITMQ_USERNAME: CHANGE_ME
    QUIZUP_RABBITMQ_PASSWORD: CHANGE_ME
  template:
    metadata:
      name: quizup-theme-secret
      namespace: quizup-prod
    type: Opaque

